site_name: Noirkelo
site_description: studyRepo学习笔记
site_author: Noirkelo
site_url: https://zh-spike.github.io/studyRepo

# Copyright
copyright: Copyright &copy; Noirkelo

repo_name: 'studyRepo'
repo_url: 'https://github.com/Noirkelo/studyRepo'

theme: 
  name: material
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  language: 'zh'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
    primary: 'blue'
    accent: 'light blue'
  icon:
    logo: material/library
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true


# Customization
extra:
  search:
    language: 'jp'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
  social:
    #- icon: fontawesome/brands/github
    #  link: https://github.com/zh-Spike
    #- icon: fontawesome/solid/paper-plane
    #  link: mailto:<zh-spike@outlook.com>

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css?v=13'
  
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - git-revision-date-localized
  - git-revision-date
  - search

plugins:
  - search:
      lang: ja
      prebuild_index: true
  - git-revision-date-localized:
      type: iso_datetime
      fallback_to_build_date: true
  - git-revision-date:
      enabled_if_env: CI
nav:
    - Home: index.md
    - About: about.md