site_name: wiki笔记
site_description: studyRepo学习笔记
# site_author: Xingding Luo
site_author: 罗兴定
site_url: https://luoxding.github.io/notes/
# Copyright
copyright: Copyright &copy; 2024 | Xingding Luo

#repo_name: 'notes'
#repo_url: 'https://github.com/luoxding/notes'

theme: 
  name: material
  features:
    - navigation.instant
    - navigation.path # path
    - navigation.sections
    - navigation.tabs # nav top目录显示在标题栏
    - navigation.top # 一键回顶 top
    - content.code.copy # 代码复制按钮
    - toc.integrate #目录放到左侧导航栏，以加宽阅读页面
    - navigation.indexes
    - content.code.annotate
  language: 'zh'
  font:
   #text: 'Fira Sans'
    text: 'Noto Serif CJK SC'
    code: 'Fira Mono'
 #palette:
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink #white
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode

#  icon:
  logo: figures/chapter_divide_and_conquer.png
  favicon: assets/linux.png

    #logo: fontawesome/brands/suse
   #logo: material/library
  # Don't include MkDocs' JavaScript.
  include_search_page: false
  search_index_only: true

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - bash
    - latex
    - html

# 页面快捷键
  shortcuts:
      help: 72    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s



# Customization
extra:
  search:
    language: 'jp'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/luoxding
    - icon: fontawesome/solid/paper-plane
      link: mailto:anthony_lambert@live.com
  generator: false #清除商标

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css?v=13'
  
# Extensions begin #############################################################################################################################################
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Extensions begin #############################################################################################################################################


plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      authors: true
      post_date_format: full # 日期格式 2024 年 1 月 31 日星期一
      authors_file: blog/.authors.yml
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "archive/{date}"
      categories_name: 分类
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"

  - search:
      lang: ja
      prebuild_index: true
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
      fallback_to_build_date: true
      timezone: Asia/Shanghai
      locale: zh
  - git-revision-date:
      enabled_if_env: CI
  - literate-nav:
      nav_file: SUMMARY.md


# mod-log: 2024-04-13_04:28